### ISSUE TITLE
No functions found because previously ignored warning now blocks all functions in host 4.25

### ISSUE THREAD

**Issue by Krucial92** [Azure/azure-functions-nodejs-library#123]
As of about 24 hours ago I have 2 function apps dev & prod which all of a sudden do not display any functions in the function apps. I am using the new v4 programming model, and have the worker indexing feature flag enabled, etc.

My CI/CD pipeline can successfully build & deploy the application to the dev environment, however no functions are found.

The interesting thing here is my prod function app stopped working a day ago also, and now it contains no functions when I did not touch it at all, no deployment was made to this environment, nothing changed although now it does not display any functions! And I can see when looking at the function apps memory usage it all of a sudden dropped off randomly 24hrs ago.

<img width="265" alt="Screenshot 2023-08-25 at 10 52 04 am" src="https://github.com/Azure/azure-functions-nodejs-library/assets/24580689/a79f39c5-e4ce-4e6f-b326-9540cf5a3b57">

What on earth is going on here, did the runtime version have a minor version bump and this is causing an issue all of a sudden? Can we please get some eyes on this issue as it seems like others are also encountering the same issue, which is an absolute show stopper for any effected production workloads.

**Comment by Krucial92** [comment]
To be able to look up my function app, here's info from app insights:

Invocation ID: 5401c43c-f0b4-477b-84c0-44db4313ae78
Event time: 25/08/2023, 09:29:44.6949652 (Local time)
Location: East US

Thanks @ejizba

**Comment by ejizba** [comment]
I'm seeing this error while your app is starting up:

> Worker was unable to load entry point "dist/src/functions/notification/MarkAsRead/__tests__/400Payload.test.js": jest is not defined

Addressing that may or may not fix your problem (related to https://github.com/Azure/azure-functions-nodejs-library/issues/85). Just curious what is your "main" field set to in package.json? You might want to clean that up as it appears to be loading a lot of files which I'm not sure you intend to happen.

I'm a little confused because I'm not seeing any change in the host version for that app over the past week, and the number of functions found is consistent. Btw, the app will scale down to zero instances (and thus the memory will also go down to zero) if there's no usage, so that alone doesn't mean there's a problem.

**Comment by Krucial92** [comment]
I'm aware of that error as it's also been happening in my local environment for some time: `Worker was unable to load entry point "dist/src/functions/**/*.js": jest is not defined` even though jest is installed as a dependency within the project (odd). Anyways the dist folder contains all of the tests hence this error, which I do need to clean up post build. Although this is not the issue as I have had this function app running for months with all of these test files in the dist folder, as well the app has been running without issue until it randomly seemed to remove all of the functions a day ago without any interference.

My main field is set to: `"main": "dist/src/functions/**/*.js",`

When I am loading this function app in the azure portal, I am not seeing any functions, they have magically disappeared and all of my endpoints are returning 404s. From the azure portal when viewing this function app, how can I see the logs from startup? E.g how can I see the output of the function app when it runs `npm start`.

The app also has a health check endpoint which is called every 15 minutes, so it definitely should not be showing an immediate drop of all memory usage which was originally consistent, to now zero over the last 24 hr period.

Thanks for helping to investigate.

**Comment by Krucial92** [comment]
If you are able to view the logs, after that error does it say:
```
[2023-08-25T00:10:24.037Z] 94 functions found
[2023-08-25T00:10:24.037Z] 94 functions loaded
```
Or does it just say they are found & not loaded? (I'm not sure how to view these logs via the portal)

**Comment by ivaaan** [comment]
Edit by @ejizba: moved to https://github.com/Azure/azure-functions-nodejs-library/issues/124

**Comment by ejizba** [comment]
@ivaaan I've moved your comment to a new issue as I think it has a different root cause: https://github.com/Azure/azure-functions-nodejs-library/issues/124

**Comment by ejizba** [comment]
Sometimes I see 40, sometimes I see 1. I'm not seeing 94.

```
2023-08-20T14:25:54.724565Z	1 functions found
2023-08-20T14:25:54.7246801Z	40 functions loaded
2023-08-22T23:13:41.8169117Z	40 functions found
2023-08-22T23:13:41.8266959Z	40 functions loaded
2023-08-22T23:13:42.1267224Z	1 functions found
2023-08-22T23:13:42.1268966Z	40 functions loaded
2023-08-24T23:29:41.5005087Z	40 functions found
2023-08-24T23:29:41.5093577Z	40 functions loaded
2023-08-24T23:29:41.7883587Z	1 functions found
2023-08-24T23:29:41.7884696Z	40 functions loaded
```

You should be able to see these in the `traces` table of your application insights instance. Depending how you created your app, you should have app insights by default. In the portal, go to the app insights resource -> then logs -> then just type `traces` in the editor and run the query

**Comment by Krucial92** [comment]
Sorry @ejizba I provided the wrong details to a different function app which does not have this issue, the actual details to look up this function app are:

Invocation ID: fff476d0-2dc5-436a-9ae6-934709ad0fe9
Event time: 22/08/2023, 14:41:20.3717055 (Local time)
Location: East US

These logs are a lot more interesting as I can see `0 functions loaded` and `No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).` logs..

I'm not sure why this would have randomly started happening and brought down my function app. Is there anything here you can see?

**Comment by Krucial92** [comment]
This is the operation ID of the last passed health check: `421b6395dd2c43d39c0d40c67bea704d` at `23/08/2023, 13:45:22.9416027 (Local time)`. After that I see some logs (read from bottom up):

```
REMOVED
```

And yes I do see the errors in relation to the test files, however this app has worked with these test files being within the dist folder for months, and no change has been made to this app recently.

**Comment by ejizba** [comment]
Ah, yeah for that app you got updated to host 4.25 which has some breaking changes as a part of https://github.com/Azure/azure-functions-nodejs-library/issues/85

Before, a single failure loading a file was ignored as a warning, but now it will block your entire app. We intentionally made this change while the v4 model was still in preview before going GA as we knew it could break some edge case apps. We checked telemetry and didn't think many apps would be affected, but apparently you're one of the unlucky few. We apologize for any inconvenience, but we heard a lot of feedback during preview about how difficult it was for people to find these silent warnings and thought this breaking change was worth some short term pain while still in preview. You should see these errors in your app insights and we will soon release an update to core tools so that you can see the same behavior locally

We have provided the app setting `FUNCTIONS_NODE_BLOCK_ON_ENTRY_POINT_ERROR` which you can set to `0` if you want the old behavior, although I would not recommend using that setting long term.

**Comment by Krucial92** [comment]
Thanks for investigating @ejizba, I can confirm that is indeed the issue. Adding that app setting in gets it running, which I'll remove and instead clean up all the test files in the dist folder.

I am interested as to why this function app got updated to host v4.25 where as some other ones I have are still on 4.24. What causes a function apps runtime version to get bumped?

**Comment by ejizba** [comment]
We rollout in stages by region, over the course of a couple weeks. From backend data, the two apps you mentioned in this thread look to be in different regions, which would explain it

**Comment by rrohm33** [comment]
EDIT: Moved to new issue: https://github.com/Azure/azure-functions-nodejs-library/issues/126

**Comment by Krucial92** [comment]
Thanks @ejizba that makes sense, appreciate your help - closing the issue.
