### ISSUE TITLE
Node.js v4 pm: Incorrect route triggered

### ISSUE THREAD

**Issue by dfberry** [Azure/azure-functions-nodejs-library#196]
I have 3 routes in a [branch for index.ts](https://github.com/dfberry/contoso-real-estate/blob/dfberry/1112-01/packages/api/src/index.ts):

* [reservations GET](https://github.com/dfberry/contoso-real-estate/blob/dfberry/1112-01/packages/api/src/index.ts#L58): `route: "reservations"
* [reservations/{id} GET](https://github.com/dfberry/contoso-real-estate/blob/dfberry/1112-01/packages/api/src/index.ts#L52): route: "reservations/{id}"
* [openapi UI GET](https://github.com/dfberry/contoso-real-estate/blob/dfberry/1112-01/packages/api/src/index.ts#L105): route: "{filename?}"

Requests to `https://scaling-guacamole-4j4qgp94g9hqxrv-7071.app.github.dev/api/reservations?userId=1bba7f62dc6343e297fc210bf6b68908&limit=10&offset=0` are catch in the openapi route. Why is that? 

I can see this in local debug. 

How does functions runtime know the difference between the two get routes and why is the get route triggering the openapi route. 
#152 

@glaucia86 FYI

**Comment by castrodd** [comment]
The issue here is that your routes are clashing.

Because you are using the route template `{filename?}` for `openapi-get`, the URL mentioned above is matching that template. In this case, `filename` is being defined as `reservations`.

In order to avoid this, you would need to redefine your route for `openapi-get`. Since it seems like you are expecting a filename, you could do the following:

```
app.get("openapi-get", {
  route: "files/{filename?}",
  authLevel: "anonymous",
  handler: openApi,
});
```

**Comment by dfberry** [comment]
@castrodd Weirdly, I think all 3 routes worked in v3 PM hitting different handlers. Is this a change in v4? 

Even without the openapi route, what is the order of operations the runtime uses to differentiate between these 2 routes? 

Reservation by reservation id
https://func-api-k4o6fqikdu5zi.azurewebsites.net/api/reservations/6553ee302a4adc7251111c2d

Reservation by user id
https://func-api-k4o6fqikdu5zi.azurewebsites.net/api/reservations?userId=505962f25343499fb95a0044175c515c

**Comment by castrodd** [comment]
I am not sure about the behavior in v3, but I can look into why that might be the case.

In terms of how these 2 routes are handled, we can see in the first case that **Reservation by reservation id** has a URL that contains `reservations/{some id}`. The inclusion of the `/` after the word `reservations` allows us to match that url with:
```
 app.get("simple-get-by-id", {
    route: "reservations/{id}",
    authLevel: "anonymous",
    handler: getReservationById,
 });
```

On the other hand, **Reservation by user id** does not include a `/`.

As soon as we hit the `?`, we know everything after that `?` is a query string. This query string will be parsed into query parameters and sent along with the rest of the request as additional information, but will not determine which API we will be routed to.

We just need to match the part of the URL that came before the query string: `https://func-api-k4o6fqikdu5zi.azurewebsites.net/api/reservations`.

And this is in fact what we defined for that API (specifically, a URL that ends with `reservations`):
```
app.get("simple-get", {
    route: "reservations",
    authLevel: "anonymous",
    handler: getReservations,
});
```

**Comment by dfberry** [comment]
@castrodd If I add that last whack, I get a 504. I would have expected a 404 from the app before hitting a handler or a 404 from inside the reservations route. This url is for a v3 pm - in case that wasn't clear. I'm running a v3 and a v4 version of the APIs to figure out why I'm getting different results.

https://func-api-k4o6fqikdu5zi.azurewebsites.net/api/reservations/?userId=505962f25343499fb95a0044175c515c

![image](https://github.com/Azure/azure-functions-nodejs-library/assets/1517008/77a5837a-56eb-4b54-8b1e-a1a61203d7c1)

**Comment by castrodd** [comment]
Yes, I would not expect that pattern to work.

A URL can end with either `reservations/{some ID}` or `reservations?{some query string}`.

A URL that contains a collection name and then `/` must be followed by data that specifies a single resource (like an id, for example). You cannot follow a `/` by a `?` because the routing is expecting some data after the `/`.

So, in the URL you mentioned above, it is saying look in the collection of resources named `reservations` and give me a specific reservation (this is what the `/` is signifying) but there is no name or id provided before the query string begins with `?`. Therefore, we are getting an error because there is no matching pattern for such a route.

You would only use the `?` to supply a query string once you have completed your base URL like `myfunc.azurewebsites.net/api/reservations` or `myfunc.azurewebsites.net/api/reservations/12345678`.

Let me know if this helps clarify things.
