### ISSUE TITLE
Errors from other functions present and maybe crashing functions

### ISSUE THREAD

**Issue by sga-solita** [Azure/azure-functions-nodejs-library#215]
We are having problems with some functions/triggers failing due to errors in other functions/triggers. Here is an example:
```
Exception while executing function: Functions.FunctionA node exited with code 1 (0x1) LanguageWorkerConsoleLog[error] Worker uncaught exception (learn more: https://go.microsoft.com/fwlink/?linkid=2097909 ): TypeError: Cannot read properties of undefined (reading 'get')
    at /home/site/wwwroot/dist/src/jobs/functions/FunctionB.js:91:56
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
```

The error from FunctionB is present in multiple other functions. FunctionB runs every minute, and crashes every time because of a bug in our code (to be fixed), but that shouldn't take down other functions.

#### Investigative information

Please provide the following:

- Timestamp: 2024-02-01T00:00:07.098654Z
- Function App name:
- Function name(s) (as appropriate):
- Invocation ID: 9471b09c-1a2c-4393-b504-ede5b02b1642
- Region: WEU

#### Repro steps

Provide the steps required to reproduce the problem:
Unable to recreate the behavior. I _think_ it is a race condition, but my own attempts to recreate it locally has failed.

#### Expected behavior

Provide a description of the expected behavior.

#### Actual behavior

Provide a description of the actual behavior observed.

#### Known workarounds

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Programming language used 
* Links to source
* Bindings used

**Comment by ejizba** [comment]
Hi @sga-solita, this is expected behavior. When an error is thrown like this it's thrown at the process level outside the context of your function. We actually have no way of knowing which function it came from and it could lead to unexpected behavior for the whole process

If you want to share your code we'd be happy to provide specific suggestions to improve it. We also have more general suggestions listed here: https://go.microsoft.com/fwlink/?linkid=2097909

**Comment by sga-solita** [comment]
@ejizba  Thanks for getting back to me. I thought that functions ran kind of isolated. So that user code wouldn't affect other functions. I did try to search for documentation on caveats for running multiple async functions at the same time, but couldn't find anything concrete.

How should I code to avoid this in the future? I want to be able to look at the "Monitor" tab, in the Portal, to see all invocations which has failed. But I don't want errors to affect other functions. It seems like I can't get both?

**Comment by ejizba** [comment]
Are you using `async` and `await` in your code? What about callbacks? Try to avoid callbacks as much as possible and use `async` and `await` instead. Most exceptions will not affect your other functions, it's only "uncaught exceptions" that are thrown outside the typical call stack that can cause problems. If you're willing to share a sample of your code I can be more helpful - these "uncaught exceptions" should be pretty rare, so it's almost easier to give specific advice for your scenario instead of general advice.

If you're not already, I would suggest using a code linter like "eslint". They have a lot of rules that will help you follow best practices to avoid uncaught exceptions. Here's an example eslint rule that makes sure you don't forget to await promises:
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md

**Comment by sga-solita** [comment]
The code we are using is a legacy system, which we have ported to Azure Functions. Turns out there was some callback code, which I have now rewritten. It looks like it has resolved the host crashing. I only thought that it was the top most code, which should follow the guidelines. Thanks for the help 😊
