### ISSUE TITLE
support for router

### ISSUE THREAD

**Issue by sukeshpabolu** [Azure/azure-functions-nodejs-library#219]
Is there a support for router like we have in express? 

#### Investigative information
Example provided

```typescript
import someController from '../controllers/some.controller';
import { Router } from 'express';

const api = Router().use('/some', someController)
            
export default Router().use('/api', api);
```

**Comment by ejizba** [comment]
No, I don't think we have something exactly like that. If you give more details on what you're trying to accomplish or specific parts you like about the express router, we might have something that accomplishes the same thing. If we don't, we could leave this open as a feature request

**Comment by sukeshpabolu** [comment]
We organise our code in the form of module/view/controller using express, you can refer to this repo for an example. https://github.com/gothinkster/node-express-prisma-v1-official-app/tree/main. You can check src/routes/routes.ts file

**Comment by ejizba** [comment]
If the primary reason you want this is so that you can more easily match your express application, then I think we can close in favor of this issue: https://github.com/Azure/azure-functions-nodejs-library/issues/16

If you don't care about express and just want the feature itself, then I would need a lot more details including what specifically you want, why you want it, and why you can't accomplish it with the existing features.
