### ISSUE TITLE
Missing Content-Type for BusBoy using Azure Function v4

### ISSUE THREAD

**Issue by crizzs** [Azure/azure-functions-nodejs-library#232]
Hello Azure,

I am faced with this issue (missing Content-Type) while using the latest version of busboy on Azure Function v4 to process form data.

Noticed azure function field name is content-type instead of Content-Type. I have no such issue on azure function v3

<img width="879" alt="Screenshot 2024-03-11 at 7 00 40 PM" src="https://github.com/Azure/azure-functions-nodejs-library/assets/3810093/15559add-aa76-48b6-8792-a648afeab2ad">

**Comment by ejizba** [comment]
Hi @crizzs can you please provide more detailed sample code? In general request headers are supposed to be case-insensitive and I think busboy will handle both casings, so I suspect something else might be causing the problem

**Comment by crizzs** [comment]
Hello ejizba,

This issue is well-publicised under another repository, @anzp/azure-function-multipart (Used them for azure functions v3). BusBoy has an if-statement that is case sensitive. This is designed due to an underlying assumption that all headers automatically lowercases all incoming headers to make them easily accessible.
https://github.com/mscdex/busboy/blob/master/lib/index.js#L52

Issue flagged out by community as well: 
https://github.com/anzharip/azure-function-multipart/issues/637

Anyways I found a workaround to get through it by turning the headers back to an object for reprocessing. This will prevent busboy from flagging out the missing Content-Type.

`Object.fromEntries(req.headers)`

**Comment by ejizba** [comment]
Right so I don't think the problem is the casing of content-type, but just the fact that our `request.query` property is now of type `URLSearchParams` which doesn't have the headers directly on the object. In other words, `request.query['content-type']` doesn't work but `request.query.get('content-type')` does.

Since busboy expects the headers to be directly on the object, I feel like your workaround `Object.fromEntries(req.headers)` is the correct/best way to do this.

Btw, if you haven't already, you could try doing `request.formData()` directly. It's less configurable than busboy, but for simple forms it'll get the job done.
