### ISSUE TITLE
Worker doesn't respect `languageWorkers:node:arguments` in v4 using placeholders in Azure

### ISSUE THREAD

**Issue by llimos** [Azure/azure-functions-nodejs-library#74]
As of this morning (March 9), all my functions stopped working. It no longer invokes Node with the arguments specified in `languageWorkers:node:arguments`. In my case, this led to the app failing to start, since I use Yarn PnP, and I use the startup args to include the PnP loader.

#### Investigative information

- Timestamp: 2023-03-09T07:00:00Z
- Function App name: tzur-portal, tzur-portal-test
- Function name(s) (as appropriate): Api
- Invocation ID: N/A, app doesn't start
- Region: West Europe

#### Repro steps

1. Using Functions runtime ~4, add a `languageWorkers:node:arguments` configuration. In my case: `"-r ./.pnp.cjs --max-old-space-size=1272 --expose-gc"`
2. Attempt to start the Functions app

#### Expected behavior

App launches correctly. The included file gets executed. The command line arguments show up in the node.exe process in the Process Explorer.

#### Actual behavior

The args are not passed to node.exe. They do not show up in the Process Explorer for the node process, and the included file is not run. In my app, this leads to no 3rd party packages being loaded. The logs show 'tslib' as the non-loaded package, because it comes first.

#### Known workarounds

I downgraded to Functions runtime ~3 and Node version ~14, after which it worked as before.

#### Related information 

* Programming language used: Typescript
* Platform: Windows
* Bindings used: HTTP

**Comment by llimos** [comment]
Pinning FUNCTION_EXTENSION_VERSION to `4.15` instead of `~4` also adequately works around the problem. This seems to be an issue only in the latest release.

**Comment by ejizba** [comment]
Hi @llimos sorry for the delayed response. I believe this may have been fixed in host v4.16.5 which we rolled out last week. Can you try switching back to `~4` and letting me know if it works now?

**Comment by ejizba** [comment]
I was able to reproduce the issue myself. 4.16.5 fixed it for me for existing apps, but not apps using the new programming model. I want to keep this issue open to track the fix for the new model - filed a corresponding issue on the host here: https://github.com/Azure/azure-functions-host/issues/9187

**Comment by llimos** [comment]
Hi @ejizba, thanks for picking this up. Yes, it's now working with `~4`.

This was a pretty major breakage in a minor version upgrade that was rolled out automatically. Are there no automated tests for this option?

**Comment by ejizba** [comment]
A basic unit test wouldn't catch this specific scenario, and no I don't think we have a more advanced end-to-end test - I can look into it. That being said, if at all possible I would encourage you to avoid using this setting in production as it has a negative effect on cold start. Basically, this setting means we have to start your worker process from scratch using your custom arguments instead of using a generic pre-warmed worker that's ready and waiting to go.

**Comment by llimos** [comment]
Ok, good to know. Thanks for your help.

**Comment by ejizba** [comment]
Old model apps were fixed a while ago. I just verified this was fixed for new model apps in host v4.21 which is currently rolling out.
