### ISSUE TITLE
Request for: Node.js Version 20 support

### ISSUE THREAD

**Issue by randomaxess** [Azure/azure-functions-nodejs-library#92]
We're slowly preparing for Node v20 to become LTS by October, and we would like for the azure-functions-nodejs-library to support node version 20 to help us migrate our multiple function apps. I know it's early but in Denmark where I live, and in non-tech enterprise setups where I work, it's actually late.

The reason we would like v20 and not v18 is to run a stable version across our stacks, and 20 offers features we need in many of our front-end applications.

It's mostly an issue for running things locally, in Azure itself it's perfectly acceptable for us to run our apps with v18 in containers, but it's causing our developers some issues.

**Comment by ejizba** [comment]
Hi @jacobaagaardbennike in order to declare official support for Node 20 we would have to support it in Azure as well, which we're [working on](https://github.com/Azure/azure-functions-nodejs-library/issues/170), but it will take some time. Unofficially, you should already be able to use this package with Node 20 locally as long as you are on core tools v4.0.5174 or higher (which looks like it just released 4 days ago). If you're still having problems running locally, let us know

**Comment by ejizba** [comment]
Closing this in favor of https://github.com/Azure/azure-functions-nodejs-library/issues/170
